---
title: "Preprocessing_QC.Rmd"
author: "Hue M. La & Fernando J. Rossello"
output: html_document
---

# Preamble
Based on the approach described [here](https://satijalab.org/seurat/articles/integration_introduction.html), example described in this [manuscript](https://www.cell.com/cell/fulltext/S0092-8674(19)30559-8)
Cluster specific responses to genoytpe?

# Prepare environment
```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, error = F, message = F, results = "hide", eval = T)
```

## Libraries
```{r import_libraries, include = TRUE, echo=TRUE, results='hide', message=FALSE}
library("Seurat")
library("tidyverse")
library("patchwork")
library("openxlsx")
library("DropletUtils")
library("tidyverse")
library("scater")
library("patchwork")
library("scDblFinder")
library("BiocSingular")
library("BiocParallel")
library("scran")
library("batchelor")
library("BiocNeighbors")
library("pheatmap")
library("bluster")


options(future.globals.maxSize= 1048576000)
bpp <- BiocParallel::MulticoreParam(workers = 16, RNGseed = 1234)
```

# Load SCE object with doublets removed.
```{r read_object}
dbl.fltrd.sts.sce <- readRDS(file ="../dbl.fltrd.sts.sce.RDS")

diet.dbl.fltrd.sts.sce <-
  SingleCellExperiment(
    assays = list(counts = counts(dbl.fltrd.sts.sce)),
    colData = colData(dbl.fltrd.sts.sce),
    rowData = rowData(dbl.fltrd.sts.sce)
  )

identical(counts(dbl.fltrd.sts.sce),
          counts(diet.dbl.fltrd.sts.sce))

identical(colData(dbl.fltrd.sts.sce),
          colData(diet.dbl.fltrd.sts.sce))

identical(rowData(dbl.fltrd.sts.sce),
          rowData(diet.dbl.fltrd.sts.sce))

rm(dbl.fltrd.sts.sce)
gc()

diet.dbl.fltrd.sts.sce$sizeFactor <- NULL
diet.dbl.fltrd.sts.sce$fastClusters <- NULL
diet.dbl.fltrd.sts.sce$label <- NULL
```

# QC
```{r scater_QA/QC}
mito.genes <- grep("^MT-", rowData(diet.dbl.fltrd.sts.sce)$Symbol)
ribo.genes <- grep("^RP[SL]", rowData(diet.dbl.fltrd.sts.sce)$Symbol)
mito.genes.names <- grep("^MT-", rowData(diet.dbl.fltrd.sts.sce)$Symbol, value = T)
ribo.genes.names <- grep("^RP[SL]", rowData(diet.dbl.fltrd.sts.sce)$Symbol, value = T)

mito.genes.ids <- dplyr::filter(rowData(diet.dbl.fltrd.sts.sce) %>% as.data.frame(), Symbol %in% mito.genes.names) %>% pull(ID)
ribo.genes.ids <- dplyr::filter(rowData(diet.dbl.fltrd.sts.sce) %>% as.data.frame(), Symbol %in% ribo.genes.names) %>% pull(ID)


cell.qc.df <-
  perCellQCMetrics(diet.dbl.fltrd.sts.sce,
                   subsets = list(mito = mito.genes,
                                  ribo = ribo.genes))

colData(diet.dbl.fltrd.sts.sce) <- cbind(colData(diet.dbl.fltrd.sts.sce), cell.qc.df)
colData(diet.dbl.fltrd.sts.sce)$aggregation_order <- gsub("_.*", "", rownames(colData(diet.dbl.fltrd.sts.sce)))

# Nuclei like processing http://bioconductor.org/books/3.13/OSCA.advanced/single-nuclei-rna-seq-processing.html
summary(diet.dbl.fltrd.sts.sce$subsets_mito_percent == 0)
```

## Fixed thresholds
```{r}
fixed.mito <- diet.dbl.fltrd.sts.sce$subsets_mito_percent > 5
table(fixed.mito)

fixed.ribo <-  diet.dbl.fltrd.sts.sce$subsets_ribo_percent > 10
table(fixed.ribo)

fixed.detected <- diet.dbl.fltrd.sts.sce$detected < 250 
table(fixed.detected)

plotColData(diet.dbl.fltrd.sts.sce, x="Sample", y="sum")

fixed.sum <- diet.dbl.fltrd.sts.sce$sum < 500 
table(fixed.sum)

plotColData(diet.dbl.fltrd.sts.sce, x="Sample", y="sum",
    colour_by=I(fixed.sum)) +
   plotColData(diet.dbl.fltrd.sts.sce, x="Sample", y="detected",
    colour_by=I(fixed.detected))

table(fixed.mito | fixed.ribo |fixed.detected | fixed.sum)
```

# Discard low quality cells.
```{r qc_discard}
cells.discard <- fixed.mito | fixed.ribo | fixed.detected | fixed.sum 
table(cells.discard)

qc.dbl.fltrd.sts.sce <- diet.dbl.fltrd.sts.sce[, !cells.discard]

plotColData(
  qc.dbl.fltrd.sts.sce,
  x = "Sample",
  y = "detected"
)

colData(qc.dbl.fltrd.sts.sce) %>% as.data.frame() %>% group_by(Sample) %>%
  summarise(median = median(sum, na.rm = TRUE)) %>% arrange(median)

summary(qc.dbl.fltrd.sts.sce$subsets_ribo_percent)
```

# Discard lowly expressed, mitochondrial and ribosomal genes.
```{r}
set.seed(1234)
keep.features <- nexprs(qc.dbl.fltrd.sts.sce, byrow = T, BPPARAM = bpp) >= 25

table(keep.features)

mito.genes.names <- grep("^MT-", rowData(qc.dbl.fltrd.sts.sce)$Symbol, value = T)
ribo.genes.names <- grep("^RP[SL]", rowData(qc.dbl.fltrd.sts.sce)$Symbol, value = T)

no.mito.ribo.genes <- !rowData(qc.dbl.fltrd.sts.sce)$Symbol %in% c(mito.genes.names, ribo.genes.names)

table(no.mito.ribo.genes & keep.features)

qc.dbl.fltrd.sts.sce <-
  qc.dbl.fltrd.sts.sce[no.mito.ribo.genes &
                          keep.features,]

dim(qc.dbl.fltrd.sts.sce)

saveRDS(qc.dbl.fltrd.sts.sce,
        file ="../qc.dbl.fltrd.sts.sce.RDS")
```
