# Packages
```{r}
library(Seurat)
library(schex)
library(ggplot2)
library(shiny)
library(dplyr)
library(patchwork)
library(rmarkdown)
library(openxlsx)
library(here)
library(SingleR)
```

# Load sts.non.malignant object
```{r}
sts.non.malignant <- readRDS("../sts.nonmalignant.RDS")
set.seed(1122)
fib.col <- distinctColorPalette(5)
fib.col <- c("#E09470","#A4D7C6","#BAA3D3","#DCC179") #,"#C05BD1")
fib.color <- setNames(object = fib.col, nm=c("CAFs_MYO","CAFs_CXCL14+", "CAFs_NRT","Vascular smooth muscle")) 
```

# PC analysis to verify FRC identity
```{r}
fib <- sts.non.malignant %>% subset(subset = Lv.1.Anno %in% c("CAFs", "Schwann","Pericytes", "FRCs","FDCs"))

Idents(fib) <- "Lv.1.Anno"
DefaultAssay(sts.non.malignant) <- "SCT"
DimHeatmap(sts.non.malignant, dims = 12, cells=500, balanced = T) 
DimHeatmap(fib, dims = 12, cells=500, balanced = T, raster = F, nfeatures = 40) 

DimPlot(fib,
        label = TRUE,
        reduction = "pca", #cols = stromal.color,
        group.by = "Lv.1.Anno",
        dim= c(1, 12)) + NoLegend() 

DimPlot(fib,
        label = TRUE,
        reduction = "pca",
        group.by = "Patient_ID",
        dim= c(1, 12)) + NoLegend() 

DimHeatmap(sts.non.malignant, dims = 1:12, cells=500, balanced = T) # PC = 12

```

## Transcriptome differences
```{r}
#Ref: https://github.com/yunshun/HumanBreast10X/blob/main/RCode/NormTotal.R
# this is to make sure we compare CAFs vs FRCs
stromal.subsets <- readRDS("../stromal.subsets.RDS")
fib <- stromal.subsets %>% subset(subset = Lv.3.Anno %in% c("Vascular smooth muscle", "unassigned"), invert=T)
DefaultAssay(fib) <- "RNA"

# Converting cluster name into numerical
Idents(fib) <- "Lv.2.Anno"
fib@meta.data$Lv.2.Anno <- as.factor(fib@meta.data$Lv.2.Anno)
print(levels(fib@meta.data$Lv.2.Anno))
levels(fib@meta.data$Lv.2.Anno) <- 1:length(levels(fib@meta.data$Lv.2.Anno))
print(1:length(levels(fib$Lv.2.Anno)))
ClusterSub <- as.factor(fib@meta.data$Lv.2.Anno) 

PatClust <- paste(fib$Patient_ID, ClusterSub, sep = "_Clst") #labelling each cell with Sample#_Cls#
counts <- fib@assays$RNA@counts #dgCMatrix
counts <- as.matrix(counts)
counts <- t(rowsum(t(counts), group=PatClust))

library(limma)
library(edgeR)
count.matrix <- DGEList(counts) 
count.matrix$samples$Patient <- gsub("_Clst.*$","", colnames(count.matrix)) #adding a new column, named Patient 
count.matrix$samples$Cluster <- as.numeric(gsub("^.*_Clst","",colnames(count.matrix))) #adding a new column, named Cluster
count.matrix$samples$group <- count.matrix$samples$Cluster
count.matrix #count matrix

# Filtering
summary(count.matrix$samples$lib.size)
#Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    725    8251   43980  435665  300830 7727883 
keep.samples <- count.matrix$samples$lib.size > 2e4
table(keep.samples)
count.matrix <- count.matrix[, keep.samples]

keep.genes <- filterByExpr(count.matrix, group=count.matrix$samples$Cluster)
count.matrix <- count.matrix[keep.genes, , keep=FALSE]

# there are 5 main cell classes: CAFs = 1; FRCs = 3
ClstSub <- count.matrix[,count.matrix$samples$Cluster %in% c("1","3")]  # the CAFs here are all CAFs for downstream analysis, without ambiguous cells
keep <- filterByExpr(ClstSub, min.count=5, min.total.count=10) #min=10, min.total.count=20 # will use #5 to minimise false positive 
table(keep)
ClstSub <- ClstSub[keep, , keep=F]
ClstSub <- calcNormFactors(ClstSub) # to calculate normalisation factors to a algin columns of a count matrix
ClstSub$samples$group

fib.col <- c("#90ADD1", "#92A36F")
plotMDS(ClstSub, pch = 16, col = fib.col[ClstSub$samples$group], main="")

#Design matrix
Cls <- as.factor(ClstSub$samples$Cluster)
Pat <- factor(ClstSub$samples$Patient)
#design <- model.matrix(~Cls+Pat)
design <- model.matrix(~0+Cls+Pat)

colnames(design) <- gsub("patient","",colnames(design))
head(design)

#Estimate NB dispersion & QL dispersion
ClstSub <- estimateDisp(ClstSub, design = design, robust=T)
plotBCV(ClstSub)
qfit <- glmQLFit(ClstSub, design)

contr <- makeContrasts(Cls3-Cls1,
    levels=design)

FRC.de <- glmQLFTest(qfit, contrast=contr)

### Extracting data table ###
FRC.de <- FRC.de$table
FRC.de$gene <- rownames(FRC.de)
write.csv(FRC.de, file =  "~/projects/PDAC_non_malignant_cell_types/output/Tables_Aug24/FRCs.vs.CAFs.deg.csv", row.names = F)
```

## Enhanced volcano 
```{r}
# features to plot
features <- c("CXCL2","PLA2G2A","HAS1","MEDAG", "IGFBP6","CXCL3","CCL2","IL6R","IL6ST","PI16","CSF1","IL1R1","IL1RAP","VCAM1",
              "C3","FGF7","CCDC80","PIM1","IGF1","MYC","GPRC5A", #iCAFs
              "LEF1","MMP11","GALNTL6","CSMD1","ZNF365","APOD", "KSR2", #FIB
              "TNFSF14","ICAM1","IL1RL1","CD34","COL11A1","TWIST1","COL10A1","ITGA11")

library(EnhancedVolcano)
EnhancedVolcano(FRC.de, x="logFC", y="PValue",
    lab = FRC.de$gene,
    title = "Differentially expressed genes in fibroblastic reticular cells (FRCs)",
    selectLab = features,
    FCcutoff = 1.25, 
    pCutoff = 0.05,
    pointSize = 4.0,
    labSize = 5.0,
    drawConnectors = TRUE,
    col = c("black","black","black","coral3"),
    ylim = c(0,12), xlim = c(-7.5,7.5),
    #colAlpha = 1,
    widthConnectors = 0.5)
```

## GSEA analysis
```{r}
library("tidyr")
library("msigdbr")
library("clusterProfiler")
library("org.Hs.eg.db")
library("ReactomePA")
frc <- FRC.de %>% dplyr::arrange(desc(logFC))
geneList <- frc$logFC # sort according to FC
names(geneList) <- frc$gene # Extract vector of gene symbol

# GSEA use ensemble ID
gene.symbols <- frc$gene
gene.entrez <- bitr(gene.symbols, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = "org.Hs.eg.db", drop = F)
colnames(gene.entrez)[1] <- "gene"
frc <- left_join(frc, gene.entrez, by = "gene")

gene_list <- frc$logFC
names(gene_list) <- frc$ENTREZID

set.seed(1245)
gse <- gsePathway(geneList = gene_list, 
                pvalueCutoff = 0.2,
                pAdjustMethod = "BH", 
                verbose = FALSE)
dotplot(gse, showCategory=30)

library(enrichplot)
gseaplot2(gse, geneSetID = c(3,7,15,29),pvalue_table = TRUE,
          color = c("#DB5D4B","#7872D9","black","seagreen"))
```

