---
title: "CellChat Analysis"
author: "Mai La"
---

# CELLCHAT - Lv.1.Anno
```{r}
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
options(future.globals.maxSize = 8000 * 1024^2)
# CellChat requires two user inputs: one is the gene expression data of cells, and the other is the user assigned cell labels.
# https://htmlpreview.github.io/?https://github.com/jinworks/CellChat/blob/master/tutorial/CellChat-vignette.html
```

## Create input files - have to subsample
Ref: https://htmlpreview.github.io/?https://github.com/jinworks/CellChat/blob/master/tutorial/CellChat-vignette.html#infer-the-cell-cell-communication-at-a-signaling-pathway-level
```{r}
sts.simspec_cs.sct <- readRDS("~/projects/PDAC_non_malignant_cell_types/output/cellbender/Aug24_objects/sts.simspec_cs.sct.RDS")
DefaultAssay(sts.simspec_cs.sct) <- "RNA"
Idents(sts.simspec_cs.sct) <- "Lv.1.Anno"
sts.simspec_cs.sct <- subset(sts.simspec_cs.sct, subset = Lv.1.Anno %in% c("Stromal (rare subtypes)", "unassigned","PDA_OLGC"), invert=T)
sts.seurat <- subset(sts.simspec_cs.sct, downsample=500) # downsample parameter here means 500 cells per idents
```

## Creating CellChat object
```{r}
cellchat <- createCellChat(object = sts.seurat, group.by = "Lv.1.Anno", assay = "RNA") # require lognormalise data
cellchat@DB <- CellChatDB.human

# Preprocessing the expression data for cell-cell communication
cellchat <- subsetData(cellchat, features = NULL) # This step is necessary even if using the whole database
future::plan("multisession", workers = 20) # do parallel
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
saveRDS(cellchat, file = "~/projects/PDAC_non_malignant_cell_types/output/cellbender/Aug24_objects/cellchat_Lv.1.RDS")
```
